[package]
name = "cli_voter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde-binary = "0.5.0"
bincode = "1.3.3"
solana-sdk = "2.0.2"
solana-client = "2.0.2"
solana-program = "2.0.2"
